### ISSUE TITLE
Make the webpage responsive

### ISSUE THREAD

**Issue by SoarinSkySagar** [AssignMate/assignmate-waitlist#1]
The current webpage is working fine on a large screen, but is not at all responsive and distorts on medium and small screens. Your job is to make it responsive such that it is displayed fine across all screen sizes.

PS.: Brownie points for the one who can do the task successfully👀

**Comment by Tonykimanthi** [comment]
Hey! Can I contribute?

**Comment by SandipGyawali** [comment]
I can work on this issue. @SoarinSkySagar can you assign me this issue?
